language: cpp
compiler: gcc
before_install:
 - sudo apt-get install -y libxml2-dev libxerces-c-dev python-svn python-lxml astyle libboost-all-dev xsdcxx default-jre libssl-dev gcc-multilib g++-multilib
 - wget --no-check-certificate https://cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
 - tar -xzvf cmake-2.8.12.2.tar.gz 
 - cd cmake-2.8.12.2
 - ./bootstrap
 - make      
 - sudo make install
 - cd ..
 - wget -O uatoolkit151.tar.gz --no-check-certificat https://cernbox.cern.ch/index.php/s/xZRLNSZluifm7uk/download
 - tar -xzvf uatoolkit151.tar.gz
 - sudo cp -R sdk/ /opt/OpcUaToolkit-1.5.1-evaluation/
script:
 - git clone -b uatoolkit_14x https://github.com/quasar-team/quasar.git
 - git clone https://github.com/quasar-team/quasar-validation-ci.git
 - mv quasar-validation-ci/CI/Design.xml quasar/Design/
 - mv quasar-validation-ci/CI/config.xml quasar/bin/
 - mv quasar-validation-ci/CI/ServerConfig.xml quasar/bin/
#links from cernbox are not permanent, be carefull
 - wget -O quasar/Design/saxon9he.jar --no-check-certificat https://cernbox.cern.ch/index.php/s/FIZm1Ew5CyxLDUd/download
 - cd quasar
 - python quasar.py generate device GreenLED
 - python quasar.py generate device YellowLED
 - python quasar.py generate device RedLED
 - sudo chmod 777 -R *
 - python quasar.py build Release ubuntu_evaluationToolkit.cmake
